project:
  type: website
  output-dir: docs



website:
  title: "Remote Debugging of Rust Programs in VS Code"
  navbar:
    left:
      - href: site/index.qmd
        text: Start
      - href: site/make-rust.qmd
        text: Rust Program + GDB
      - href: site/manual-rdbg.qmd
        text: Remote Debug
      - href: site/vscode-setup.qmd
        text: VS Code
      #- site/index.qmd
      #- site/manual-rdbg.qmd
      #- site/vscode-setup.qmd

format:
  html:
    theme:
      dark:   [ slate, site/dark-monospace-style.scss ]
      light:  [ slate, site/dark-monospace-style.scss ]
    toc: true
    
    code-annotations:   true
    code-line-numbers:  false
    code-overflow:      scroll
    code-fold:          false


# Gettin muh tufte on
reference-location: margin
citation-location: document
tbl-cap-location: margin
cap-location: margin
