project:
  type: website
  output-dir: docs



website:
  title: "Rust Remote Debugging in VS Code"
  navbar:
    left:
      - href: site/index.qmd
        text: Start
      - href: site/make-rust.qmd
        text: 1. Code & Gdb
      - href: site/xcomp-rdbg.qmd
        text: 2. X-Comp & Remote Gdb
      - href: site/vscode-setup.qmd
        text: 3. VS Code
      #- site/index.qmd
      #- site/xcomp-rdbg.qmd
      #- site/vscode-setup.qmd

format:
  html:
    theme:
      dark:   [ slate, site/dark-monospace-style.scss ]
      light:  [ slate, site/dark-monospace-style.scss ]
    toc: true
    
    highlight-style:    nord
    code-annotations:   true
    code-line-numbers:  false
    code-overflow:      scroll
    code-fold:          false


# Gettin muh tufte on
reference-location: margin
citation-location: document
tbl-cap-location: margin
cap-location: margin
